### ISSUE TITLE
Remove references to chain

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-exception-cpp#28]
As a Koinos Engineer, it annoys me that exception-cpp contains references to chain, when it is a library and not a microservice.

- [ ] Remove declaration of chain exceptions in exception-cpp
- [ ] Move chain `error_data` to koinos package in proto
- [ ] Fix reference to `error_data` in exception-cpp
- [ ] Fix reference to `error_data` in chain
- [ ] Remove use of chain exceptions in state-db-cpp
- [ ] Catch state-db exceptions and wrap in reversion exceptions

**Comment by sgerbino** [comment]
Closed to a change in strategy.
